image: Previous Visual Studio 2017

build_script:
  - ps: .\windows\build.ps1

deploy_script:
  - ps: echo "$Env:DOCKER_PASSWORD" | docker login --username "$Env:DOCKER_USERNAME" --password-stdin 
  - ps: docker push $Env:DOCKER_TAG

clone_depth: 1
test: off

