image: Visual Studio 2017

build_script:
  - ps: .\windows\build.ps1

deploy_script:
  - docker login --username "$Env:DOCKER_USERNAME" --password "$Env:DOCKER_PASSWORD"
  - docker push $Env:DOCKER_TAG

clone_depth: 1
test: off

